runtime: nodejs20
service: default

env_variables:
  VITE_API_URL: "https://genai-strategy-class-backend-ue.a.run.app"

handlers:
  - url: /assets
    static_dir: dist/assets
    secure: always
  - url: /vite.svg
    static_files: dist/vite.svg
    upload: dist/vite.svg
    secure: always
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always 