apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: competitor-analysis-backend
spec:
  template:
    spec:
      timeoutSeconds: 600
      containers:
      - image: gcr.io/genai-strategy-class/competitor-analysis-backend
        ports:
        - containerPort: 8000
        command: ["uvicorn"]
        args: ["main:app", "--host", "0.0.0.0", "--port", "8000", "--timeout-keep-alive", "75"]
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-api-key
              key: latest
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-secret-key
              key: latest
        - name: CORS_ORIGINS
          value: "http://localhost:5173,http://localhost:5174,http://localhost:5175,http://localhost:5176,http://localhost:5177,http://localhost:5000,https://competitor-analysis-frontend-342114956303.us-central1.run.app"
        - name: AUTH_USERNAME
          valueFrom:
            secretKeyRef:
              name: auth-username
              key: latest
        - name: AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-password
              key: latest
        - name: GCS_BUCKET_NAME
          value: "competitor-analysis-uploads"
        resources:
          limits:
            cpu: "2"
            memory: "1Gi"
          requests:
            cpu: "1"
            memory: "512Mi" 